<?php 
if($this->status != ''){ 
$alerta = explode("|", $this->status);
?>
<div class="<?= $alerta[0] ?>" role="alert">
	<?= $alerta[1] ?>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
</div>
<?php } ?>
<form id="frm-demanda" method="post" action="<?= $_SERVER['SCRIPT_NAME'];?>/demanda/cadastra" enctype="multipart/form-data">
	<div class="form-row">
		<?php if($this->id){ ?>
		<div class="form-group col-md-2">
		  <label for="NUMERO_SGD">Número SGD</label>
		  <input type="text" class="form-control" id="NUMERO_SGD" name="NUMERO_SGD" readonly>
		  <input type="hidden" id="ID" name="ID" value="<?=$this->id?>" />
		</div>
		<?php } ?>
		<?php if(!$this->id){ ?>
		<div class="form-group col-md-3">
		  <label for="SGD_MASCARA">SGD Máscara<a id="buscarDemanda" href="#"><i class="fas fa-search fa-lg"></i></a></label>
		  <input type="text" maxlength="10" class="form-control numero" id="SGD_MASCARA" name="SGD_MASCARA">
		</div>
		<?php } ?>
		<div class="form-group col-md-3">
		  <label for="DEMANDANTE">Demandante</label>
		  <input type="text" class="form-control" readonly id="DEMANDANTE" name="DEMANDANTE" value="<?=utf8_encode($_SESSION['Zend_Auth']['storage']['nome'])?>">
		</div>
		<div class="form-group col-md-3">
		  <label for="DIRETORIA">Área</label>
		  <input type="text" class="form-control" readonly id="DIRETORIA" name="DIRETORIA" value="<?=$_SESSION['Zend_Auth']['storage']['diretoria']?>">
		</div>
		<div class="form-group col-md-3">
		  <label for="EMAIL">E-mail</label>
		  <input type="EMAIL" class="form-control" readonly id="EMAIL" name="EMAIL" value="<?=$_SESSION['Zend_Auth']['storage']['email']?>">
		</div>
		<div class="form-group col-md-5">
		  <label for="TITULO">Título</label>
		  <input type="text" class="form-control" id="TITULO" name="TITULO" maxlength="100">
		</div>
		<div class="form-group col-md-4">
		  <label for="MODALIDADE_TIPO">Modalidade</label>
		  <?php echo $this->formElementos->MODALIDADE_TIPO; ?>
		</div>
		<div class="form-group col-md-3">
		  <label for="NUMERO_SCT">Número SCT</label>
		  <input type="text" class="form-control numero" id="NUMERO_SCT" name="NUMERO_SCT" maxlength="50">
		</div>
		<div class="form-group col-md-3">
		  <label for="NUMERO_SEI">Número SEI</label>
		  <input type="text" class="form-control" id="NUMERO_SEI" name="NUMERO_SEI" maxlength="50">
		</div>
		<div class="form-group col-md-3">
		  <label for="NUMERO_PADO">Número PADO</label>
		  <input type="text" class="form-control" id="NUMERO_PADO" name="NUMERO_PADO" maxlength="50">
		</div>
		<div class="form-group col-md-2">
		  <label for="PRAZO">Prazo</label>
		  <input type="text" class="form-control data_mask" id="PRAZO" name="PRAZO">
		</div>
		<div class="form-group col-md-2">
		  <label for="PRAZO_CONSIDERADO">Prazo considerado</label>
		  <input type="text" class="form-control data_mask" id="PRAZO_CONSIDERADO" name="PRAZO_CONSIDERADO">
		</div>
        <div class="form-group col-md-2">
		  <label for="FATOR_GERADOR_ID">Fator gerador</label>
		  <?php echo $this->formElementos->FATOR_GERADOR_ID; ?>
		</div>
		<div class="form-group col-md-2">
		  <label for="MULTA">Multa</label>
		  <select id="MULTA" name="MULTA" class="form-control">
			<option value="" selected>Selecione...</option>
			<option value="S">Sim</option>
			<option value="N">Não</option>
		  </select>
		</div>
		<div class="form-group col-md-2">
		  <label for="REGIAO_ID">Região</label>
		  <?php echo $this->formElementos->REGIAO_ID; ?>
		</div>
		<div class="form-group col-md-2">
		  <label for="UF">UF</label>
		  <?php echo $this->formElementos->UF; ?>
		</div>
		<div class="form-group col-md-6">
		  <label for="CLASSIFICACAO_ID">Classificação<span id="info">?</span></label>
		  <?php echo $this->formElementos->CLASSIFICACAO_ID; ?>
		</div>
		<div class="form-group col-md-3">
		  <label for="DOCUMENTO_TIPO_ID">Tipo documento</label>
		  <?php echo $this->formElementos->DOCUMENTO_TIPO_ID; ?>
		</div>
		<div class="form-group col-md-3 fisc">
		  <label class="fisc" for="FISC_PRE_ONSITE">Fiscalização pres OnSite</label>
		  <select id="FISC_PRE_ONSITE" name="FISC_PRE_ONSITE" class="form-control">
			<option value="" selected>Selecione...</option>
			<option value="S">Sim</option>
			<option value="N">Não</option>
		  </select>
		</div>
		<div class="form-group col-md-3 fisc">
		  <label class="fisc" for="FISC_REQ_OFFSITE">Fiscalização Req Info OffSite</label>
		  <select id="FISC_REQ_OFFSITE" name="FISC_REQ_OFFSITE" class="form-control">
			<option value="" selected>Selecione...</option>
			<option value="S">Sim</option>
			<option value="N">Não</option>
		  </select>
		</div>
		<?php if($this->id){ ?>
		<div class="form-group col-md-3">
		  <label for="STATUS_ID">Status</label>
		  <?php echo $this->formElementos->STATUS_ID; ?>
		</div>
		<div class="form-group col-md-2">
		  <label for="DATA_CADASTRO">Data Cadastro</label>
		  <input type="text" class="form-control" id="DATA_CADASTRO" name="DATA_CADASTRO" readonly>
		</div>
		<div class="form-group col-md-4">
		  <label for="DEMANDADO">Demandado</label>
		  <?php if($_SESSION['Zend_Auth']['storage']['perfis'] == 1){ ?>
			<a id="delegar" href="#" idDemanda="<?=$this->id?>" title="Delegar" class="iconMargem"><i class="fas fa-user-check"></i></a>
		  <?php } ?>
		  <input type="text" class="form-control" id="DEMANDADO" name="DEMANDADO" readonly>
		</div>
		<?php } ?>
    </div>
    <?php if($this->id){ ?>
    <div class="form-row" id="dilatacoes">
    </div>
		<?php } ?>
    <div class="form-row">
		<div class="form-group col-md-3">
		  <label for="OBICE">Óbice</label>
		  <select id="OBICE" name="OBICE" class="form-control">
			<option value="" selected>Selecione...</option>
			<option value="S">Sim</option>
			<option value="N">Não</option>
		  </select>
		</div>
	</div>
	<div class="form-row">
		<?php if($this->id){ ?>
		<div class="form-group col-md-4">
		  <label class="OBSERVACAO" for="OBSERVACAO">Observação</label>
		  <textarea class="form-control" rows="5" id="OBSERVACAO" name="OBSERVACAO"></textarea>
		</div>
		<?php } ?>
		<div class="form-group col-md-4 obice_desc">
		  <label class="obice_desc" for="OBICE_DESCRICAO">Descrição Óbice</label>
		  <textarea class="form-control" rows="5" id="OBICE_DESCRICAO" name="OBICE_DESCRICAO" maxlength="1000"></textarea>
		</div>
		<div class="form-group col-md-4">
		  <label for="DESCRICAO">Descrição</label>
		  <textarea class="form-control" rows="5" id="DESCRICAO" name="DESCRICAO" maxlength="1000"></textarea>
		</div>
	</div>
	<div id="arquivos" class="form-row">
		<div class="form-group col-md-3">
		 <a id="add_file" href="#"><i class="fas fa-plus"></i>Add arquivos</a>
		</div>
		<!--<div class="form-group col-md-4">
			<input class="form-control upload" type="file" name="anexo[]" id="anexo[]">
		</div>-->
	</div>
	<?php if($this->id){ ?>
	<div id="anexos" class="row"></div>
	<?php } ?>
	<div class="form-row">
		<div class="form-group col-md-12 text-right">
			<input id="salvar" type="button" class="btn btn-primary" value="Salvar" />
		<!--<button type="submit" class="btn btn-primary">Sign in</button>-->
		</div>
	</div>
</form>

<!--<script type="text/javascript" src="<?=ROOT_PATH?>/js/demanda/frm.js"></script>-->
<script>
	var url = "<?=ROOT_PATH?>/js/demanda/frm.js";
	$.getScript(url);
</script>

